apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-ingress
  namespace: flux-system
spec:
  releaseName: weave-gitops-ingress
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: HelmRepository
        name: selfhosted-manifests
        namespace: default
  interval: 15m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      tls:
        - hosts:
            - dashboard.themisha.dev
      hosts:
        - host: dashboard.themisha.dev
          paths:
            - path: /(.*)
              pathType: Prefix
              serviceName: "ww-gitops-weave-gitops"
              servicePort: 9001
