apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: weave-gitops-values
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgCXbegtvJoxnnttxXYp6Ptqv9Z9rMl2F3eDNuZR+0sU6mEFotcbbhS19quarLi0kYchb2VhJ5qHhI8+u+CeaiOC795HRH46c+Fu5NGlh63a47J2LmUVDk5mY9Ix3jyUFq3ZavjfzsOpqBsCnh7D7boYgGaEm8Py7BXwu9vO8a3U6q/cjFez3R+Iu6yu5/uYBm0Y/xwmwBeXssUY5BrGrWkSAtgxPGdLvVzwUOsP99vDRXgmnkDTyKMo8KP48D5a9YnCpl/o2GUodo4CrxXWGYlO9P0g4HFGnhGU0b1McmtypjTAcICKT4Zmvp9i1owLhAskjus+gtGGEoH9pdO9wKuGPB5QENYhc2NQzcR/+7N4CyJQImpdTegU6I9XxqZOY2qfSVlL5xXx7h6bQ0FBiSzebSiy2NkT4pjTeCC1bVu/PVStfLqGFS9KeiqejuO6XwGSisWhs+8XIpAg/cnXbAUOzb+dpyoKENlfm2aHrUJnAtRjWaG83nASlaDKJn38xMiqnxi+TTRWkSdGVygzW0ojnNMF1NuPpVQsFfZL8covIWPSQY3mTPdnS0ZpxMlbvTdZnskrQL4DWzWsMX3japHSsxfL7D2RVbgt5MGrbZlRgFZTCiMI0oz5E+yrY6TKu4MEFzz/ROs/jISYiBWVZCckjqPYdHBYE1kBRzi7L5SWW4QUV2e9+IAdZE/Z2+NF0/gpJp7I/2Qoo5pvsG++B57/0KWdjwZqhgJe7/8jq2+FBvX5vFMYi1gkQpTiRkoaH/cAqNz37Lde7netIaGxsdxEP0z+j0haOP6IO1XDNhYdH0lidCCjgM+SuIPobgKjd5PNFNgAb2oVVV6D/8/xCQd6GQzs+LEK6tc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: weave-gitops-values
      namespace: flux-system
    type: Opaque

