apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: weave-gitops-values
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgArMusXW81HOnzV/sICDGBq8jq5Ff8gi1/tz3jkTxLKQCeXCcFva1ukGWWZQlRrvu/f3Ci6EsaqeIpOhriqRCtg2TJ8uqhVvDWQ9DPHlIGr017KB6TDptN/heJ0Ff9mlv+H3JjHV2+nfeybLxq/cSAEzRzQ7scqPQQBLrAoMT90w5f0XjwCHI2z77NlZ7CGJ6VvX71ffDKxo9bUdTfJfShCUGIF7iRfxcELQr+ZUDc20SHNZVjsJFWNoyWtYDEdO0THMC2y21sZHcwI1drrbaimOdHyXyGUpks84q/NehR05VqwS7Xdy8r9ol18P/W4kib0W/9eRct/moCi/WqDei2fHS5VYhlGFlnpwPVgV07RzZZhyweEeBLE+pzsB9GmYFdUc520h9M/ePIL5dEA56nq1sIlovzzD/Zi6rQ45pA4PMf6hk9PxGOFNXLGjrX36mupm95/ttdCsLPZ8x+bPWd4ZLLS8gIr07gN+Zh/r9tAj8kec3b0c5YYQTa5faee+GGZzTqgB//AH+xpCpjgKszIJky6Lj1Vi5preqUOyt6I+BXRS7CDYJhY3snjCPTiKBRjtT3IqQD+b4AlaeiiN7JgUVCXLbVyp0W3B2cwrdcnVbGaJ85erlNzcX79HMa0FVFFUDXAChjccAYMg3gcgEBDYS2MamXGn9v+DiNGrIeoFU5E5h7RG8kf9qUrkiX8PP8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: weave-gitops-values
      namespace: flux-system

