---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql-operator
  namespace: kube-system
spec:
  chart:
    spec:
      chart: mysql-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
        namespace: flux-system
  interval: 1m0s
