apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-value-overrides
data:
  values.yaml: |
    ghost:
      nodeEnv: production
      timezone: UTC
      url: https://lazebny.io
      storage: 1Gi
      mount: /var/lib/ghost
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$1
          external-dns.kubernetes.io/target: lazebny.io
        hosts:
        - host: lazebny.io
          paths:
          - path: /(.*)
            pathType: Prefix
      image:
        repository: ghost
        tag: 5.75.0
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        port: 80
      mail:
        from: "lazebny.io <"
        transport: SMTP
        host: smtp.eu.mailgun.org
        port: 587
        auth:
          # or use secret reference for password and
          privateSecretRef: ghost-mail

    mysql:
      size: 8Gi
      image:
        repository: mysql
        tag: 8.0.33-debian
        pullPolicy: IfNotPresent
      connection:
        # mysql-database
        # mysql-username
        # mysql-password
        # mysql-root-password
        privateSecretRef: ghost-mysql
      mount: /var/lib/mysql
    
    backup:
      enabled: true
      # specify
      # S3_SECRET_ACCESS_KEY
      # S3_ACCESS_KEY_ID
      # S3_BUCKET
      # S3_REGION
      awsSecretRef: ghost-backup
      schedule: "20 4 * * *" # every day at 1am
      retentionDays: 10
      ttlSecondsAfterFinished: 86400
      
