apiVersion: v1
data:
    password: ENC[AES256_GCM,data:PKq2HrVr4FLg4IbquGfvl80NxocIhNfm,iv:PxlzW2WH6mpggdyGF9wEJadQM2EG+JuwRColwhCYcJE=,tag:QBwBCNeMqV4Ln8UtHhksRQ==,type:str]
    username: ENC[AES256_GCM,data:BSDUdoL6xeYfXdvtOflo0xhiuJyjvVnhzWNinw==,iv:URUY6mGF+gB1bbytChI56ylOcR/V337q/mEBOU1R/9c=,tag:/C5O7ZFEYJkesrB9f4qodA==,type:str]
kind: Secret
metadata:
    name: ghost-mail
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wuhwmhppza9qpv9xmu9wp8pt399q687y28ftwjkhx7tv4cs7vf3qmt8fr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaEVEOEFMTkRCdVRtUGNJ
            NXVCc01XMk1uaGlXaldRaE9oelBlNmxCaGlrClBpTkkrRVN0dzdOTGsxeGNJWGJQ
            aUdTTzhUTy9IeStyaHgvQmw1Vkd1ekEKLS0tIG0ybGw5SmEwOWp3YnJCWGhEU09B
            VEhCalp2VFBOcGV1NFZCRG15M1hrekkKa+iMu8oqfl9k0kDjvuy65lZrLUBDDSYk
            HX/P7+hefgxBiC5x2MkK6cb/Se73SbArRrnTc4QsJZZviAQNy3Hrfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T08:51:02Z"
    mac: ENC[AES256_GCM,data:D24EsEUTVKxxOEIEg7k3MROgtNQ9k5c1Ms6L9fdwerm513CqRj5tG2U3I8wG+Pc3TBPhMtfc57mOXzlC2nh503JGgnTRKR5KU8uZVwgu2JVS/HVXiVaHfta9VOVHtG0vpZX1gJGpGPuZzyIvgcfh2BroBnWgRjLEa7Lkc9aOjIY=,iv:5yjx3rvbhYg0vCt9R7ZJDP+qStm84Ayyy1aKjlGTDGM=,tag:bdsZ4chomWhnTbiyRYdilQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
