apiVersion: v1
data:
    username: ENC[AES256_GCM,data:2888okENP5C1BHG5/rXi5iAJN2zSkoO774CZda4kxHvc9MzCVPXT+Q==,iv:FUBBkq3Gx5R4+SOw7ZPQdgwk2VihsHUPWKFEyCvqjlg=,tag:0EiskPhddkA8sy6KD/yWpQ==,type:str]
    password: ENC[AES256_GCM,data:2/3lpj8pxEpKYuYuOeifHAPwBeqBfa6RdRrWqIVmxkoKs3WPnSO9twVEMJNcivZQRVK8uTf4FpDS8w2epow5Vau1mPw=,iv:tAT7RdBUhKmGb96at0038G9tndfmm8V253MHqRRlDwA=,tag:9SIouO5pZRLfb8Qq8MO0TQ==,type:str]
kind: Secret
metadata:
    name: ghost-mail
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wuhwmhppza9qpv9xmu9wp8pt399q687y28ftwjkhx7tv4cs7vf3qmt8fr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a3hMZk05bGhiQVpoeXgy
            K0ticGJzWUxUTlhCRlhYU3VwTlBldVZnWjFRCk4zZkhQWGNEbzRhZHN3bUt5ZlMx
            NlI3QytCOUFSTFRVWmVBWklGZlREbEUKLS0tIFdzYnNQeGVickhLUFM5WkNjd09x
            VXlHcm1hMUQ5bWp2NGc5cVo2Vk9HWlkK364SjQRjdCfvVTYnPpVODnCYH/5sB8IC
            NdGQ0N6C37aOKt+IWuF4FbeTbANRKH+13k+mzQ9Y0AdPbpxxG4z8vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-04T19:50:50Z"
    mac: ENC[AES256_GCM,data:RxTJjroIWjkVv/k3kK9XnV8LjARm4UtyDXVzKFLjl8iMUKHl5BCbGg2vNInNMWKicd+6q2RnRTD4+RheFkrHZw8X/8lFzIRvs5A25Rk2JurQuzlo7X1uhc4UY7G1Is6XbFJwXWi11jXJO+ySIq0+BNx0n367s2nOxB64Bn9YflQ=,iv:m1QMU7EHFtlLXL8/kJq9wPxmbKNYseetUkUCRmkn+/g=,tag:sU+oqn4EI+JxciuvxvZq6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
