apiVersion: v1
data:
    password: ENC[AES256_GCM,data:HvSGI+jcX1TKdh20yPrPrQ1aVBrlPHDxqhKG3w==,iv:BbJTDwPmN6+h3y3d7ehji9FVlr6xUDmxhKk01LO3jBc=,tag:4QQ6z6sq6CMDH/yGwSiyqQ==,type:str]
    username: ENC[AES256_GCM,data:wPIF+4R0CYzhxXtvbQOyb3ON8hVnE3WyuevFVg==,iv:1xqWMQACD+nXo/DBSO8oqc+9+eH+g7r8QzNZgbOaWXk=,tag:TFrBle97IJU+CpWLwL9cAA==,type:str]
kind: Secret
metadata:
    name: ghost-mail
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wuhwmhppza9qpv9xmu9wp8pt399q687y28ftwjkhx7tv4cs7vf3qmt8fr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bi9scTd2UmkzcitLdlhS
            SmJnTVNwNkMxSEVFVzh0alIyV1V5WGxpbFRNCmRnYlM3dmRrWjh4Tk5wTzBOcURj
            anNRcW52eWNaQndXbzM2RGVuaGJjMk0KLS0tIFpKZmtPSWd5czA3aHNBdm04UTFL
            bVdPSmZ1UnVDNXc2RjNsK1MvcG96dG8KjKgkocXZzK2Coh9jGbd2X2IaiRBSart5
            gM7nvSzn/DmmzOTlt4EBBPzRn52HEyk/uj9ML0UNHCXvbqy5DMPdhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T10:07:36Z"
    mac: ENC[AES256_GCM,data:1ey2L3w1XF6qtnt2PFYwyGgDx3/N+XY0qGmWyKN5kc7G2HUICfRqT43GDmC5f7r3zhB5mvmdXTp0IXf0CC4nQtnQDoWpSlIo6DPaVtzHRO1bxiNFKFaW4fJSA1xIgJR+occh4mrERAxJoZuA4liTk+o2iwQoe3TwSRRqb4TgG8w=,iv:Gv2Rd8M9DySg/VsCPy1aTouTWVdtSSRH0R21D4e4T1c=,tag:oZFPOAWEijX39qCp0lWXZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
