apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - "configmap-ghost-value-overrides.yaml"
  - "ghost-backup.sops.yaml"
  - "ghost-mail.sops.yaml"
  - "ghost-mysql.sops.yaml"
  - "helmrelease.yaml"
  