apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-gpt-value-overrides
  namespace: chat-gpt
data:
  values.yaml: |
    container:
      port: 3000
    resources:
      requests: 
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 500Mi
