apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-gpt
  namespace: chat-gpt
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chat.themisha.dev
  rules:
    - host: chat.themisha.dev
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: chat-gpt
                port:
                  number: 3000
