apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chat-gpt-ingress
  namespace: chat-gpt
spec:
  releaseName: chat-gpt-ingress
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: HelmRepository
        name: selfhosted-manifests
        namespace: default
  interval: 15m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      name: "chat-gpt-ingress"
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      tls:
        - hosts:
            - chat.themisha.dev
      hosts:
        - host: chat.themisha.dev
          paths:
            - path: /(.*)
              pathType: Prefix
              serviceName: "chat-gpt"
              servicePort: 3000
