apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chat-gpt-ingress-minion
  namespace: chat-gpt
spec:
  releaseName: chat-gpt-ingress-minion
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: HelmRepository
        name: selfhosted-manifests
        namespace: default
  interval: 15m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      name: "chat-gpt-ingress-minion"
      className: "nginx"
      annotations:
        nginx.org/mergeable-ingress-type: "minion"
      hosts:
        - host: chat.themisha.dev
          paths:
            - path: /(.*)
              pathType: Prefix
              serviceName: "chat-gpt"
              servicePort: 3000
