version: "3"

tasks:
  flux:secret:
    desc: "Create secret for the Git repository"
    dotenv: [".env"]
    cmds:
      - flux create secret git flux-system-creds --url=$REPOSITORY --private-key-file=$KEYFILE
    silent: true

  flux:bootstrap:
    desc: "Bootstrap Flux"
    dotenv:
      - ".env"
    cmds:
      - flux bootstrap git --url=$REPOSITORY --branch=$BRANCH --path=kubernetes/flux/config --private-key-file=$KEYFILE
    silent: true
  
  provision:cluster:
    desc: "Provision the cluster"
    summary: > 
      Provision the cluster using pulumi: create all the resources in hcloud.
    silent: true
    dir: "provision/pulumi"
    cmds: 
      # Skipping preview because of https://github.com/pulumi/pulumi-hcloud/issues/175
      - pulumi up --yes --skip-preview
  
  provision:destroy:
    desc: "Destroy the cluster"
    summary: > 
      Destroy the cluster using pulumi: destroy all the resources in hcloud.
    silent: true
    dir: "provision/pulumi"
    cmds:
      - pulumi destroy --yes