version: "3"

tasks:
  init:pre:
    prompt: "Pre-initing..."
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "Pre-initing..."
      - echo "Setup sops private key"
      # create flux-system namespace if not exists
      - kubectl create ns flux-system --dry-run=client -o yaml | kubectl apply -f -
      - cat $AGEKEY_PATH | kubectl create secret generic sops-age --from-file=age.agekey=/dev/stdin -n flux-system
      - flux check --pre
  init:post:
    prompt: "Post-initing..."
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "Post-initing..."
      - echo "Setup flux-system"
      - |
        flux bootstrap github \
          --owner=$GITHUB_USER \
          --repository=$GITHUB_REPO \
          --branch=main \
          --path=./kubernetes/flux \
          --personal \
          --components-extra=image-reflector-controller,image-automation-controller \
          --version=latest \
          --verbose