version: "3"

tasks:
  flux:secret:
    desc: "Create secret for the Git repository"
    dotenv: [".env"]
    cmds:
      - flux create secret git flux-system-creds --url=$REPOSITORY --private-key-file=$KEYFILE
    silent: true

  flux:bootstrap:
    desc: "Bootstrap Flux"
    dotenv:
      - ".env"
    cmds:
      - flux bootstrap git --url=$REPOSITORY --branch=$BRANCH --path=kubernetes/flux/config --private-key-file=$KEYFILE
    silent: true

  provision:packer:
    desc: "Create Talos OS image in Hetzner Cloud"
    summary: >
      Launches server in Hetzner Cloud, installs Talos OS, and creates image.
      Needs [HCLOUD_TOKEN] in .env file or environment variable.
    dotenv:
      - ".env"
    cmds:
      - if [[ -z "$HCLOUD_TOKEN" ]]; then echo "HCLOUD_TOKEN env variable must be set!"; exit 1; fi
      - packer build provision/packer
    silent: true

  provision:terraform:apply:
    desc: "Provision Kubernetes cluster in Hetzner Cloud"
    summary: >
      Creates Kubernetes cluster in Hetzner Cloud. 
      Needs [HCLOUD_TOKEN] and [TF_VAR_hcloud_image] in variables.tfvars file.
      Must be ran after provision:packer.
    silent: true
    cmds:
      - terraform -chdir=provision/terraform init
      - terraform -chdir=provision/terraform plan -var-file=variables.tfvars
      - terraform -chdir=provision/terraform apply -var-file=variables.tfvars
  
  provision:terraform:destroy:
    desc: "Destroy Kubernetes cluster in Hetzner Cloud"
    summary: >
      Destroys Kubernetes cluster in Hetzner Cloud. 
    silent: true
    cmds:
      - terraform -chdir=provision/terraform destroy -var-file=variables.tfvars
