apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
spec:
  releaseName: n8n
  chart:
    spec:
      chart: n8n
      sourceRef:
        kind: HelmRepository
        name: open-8gears
        namespace: flux-system
  interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: n8n-value-overrides
      valuesKey: values.yaml