apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-value-overrides
data:
  values.yaml: |
    ingress:
      enabled: true
      className: nginx
      annotations:
         nginx.ingress.kubernetes.io/rewrite-target: /$1
         external-dns.kubernetes.io/target: n8n.lazebny.io
      hosts:
        - host: n8n.lazebny.io
          paths:
            - path: /(.*)
              pathType: Prefix
    persistence:
      enabled: true
    env:
      - name: N8N_BASIC_AUTH_ACTIVE
        value: "false"
      - name: TZ
        value: UTC
      - name: N8N_HOST
        value: n8n.lazebny.io
      - name: N8N_PROTOCOL
        value: https
      - name: NODE_ENV
        value: production
      - name: WEBHOOK_URL
        value: https://n8n.lazebny.io