apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-value-overrides
data:
  values.yaml: |
    ingress:
      enabled: true
      annotations:
         kubernetes.io/ingress.class: nginx
         nginx.ingress.kubernetes.io/rewrite-target: /$1
         external-dns.kubernetes.io/target: n8n.lazebny.io
      hosts:
        - host: n8n.lazebny.io
          paths:
            - path: /(.*)
              pathType: Prefix
    persistence:
      enabled: true
    extraEnv:
      GENERIC_TIMEZONE: Europe/Warsaw
      TZ: Europe/Warsaw