apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-value-overrides
data:
  values.yaml: |
    image:
      repository: n8nio/n8n
      pullPolicy: IfNotPresent
      tag: "0.236.3"
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        external-dns.kubernetes.io/target: n8n.lazebny.io
      hosts:
        - host: n8n.lazebny.io
          paths:
            - path: /(.*)
              pathType: Prefix
    persistence:
      enabled: true
    env:
      N8N_BASIC_AUTH_ACTIVE: "false"
      TZ: UTC
      N8N_HOST: n8n.lazebny.io
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: https://n8n.lazebny.io
