apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./bitnami.yaml"
  - "./jetstack.yaml"
  - "./ingress-nginx.yaml"
  - "./podinfo.yaml"
  - "./sealed-secrets.yaml"
  - "./selfhosted-manifests.yaml"
  - "./external-dns.yaml"
  - "./stakater.yaml"
  - "./dex.yaml"