apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
resources:
  - namespace-sealed-secrets.yaml
  - helmrepository-sealed-secrets.yaml
  - helmrelease-sealed-secrets.yaml
  - sealed-secret.yaml
