---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/name: bitnami-nginx
    app.kubernetes.io/part-of: bitnami
  name: nginx
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/nginx