apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-gpt-value-overrides
  namespace: chat-gpt
data:
  values.yaml: |
    service:
      port: 3000
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        external-dns.kubernetes.io/target: chat.lazebny.io
      hosts:
          - host: chat.lazebny.io
            paths:
              - path: /(.*)
                pathType: Prefix
    resources:
      requests: 
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 500Mi
        