---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: percona-operator
  namespace: percona
spec:
  chart:
    spec:
      chart: pxc-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
  interval: 1m0s
