---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
  path: ./kubernetes/apps/networking/ingress-nginx/certificates
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nginx-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-sealed-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/networking/ingress-nginx/app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: networking
  prune: true
  interval: 15m
  timeout: 2m
