apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-value-overrides
  namespace: nginx
data:
  values.yaml: |
    ingress: 
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        external-dns.kubernetes.io/target: proxy.lazebny.io
      hostname: proxy.lazebny.io
      path: /(.*)
      pathType: Prefix
    serverBlock: |
      server {
        location /discord/ {
            proxy_pass https://discord.com/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
