apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-value-overrides
  namespace: nginx
data:
  values.yaml: |
    ingress: 
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        external-dns.kubernetes.io/target: proxy.lazebny.io
      hostname: proxy.lazebny.io
      path: /(.*)
      pathType: Prefix
    service:
      type: ClusterIP
    serverBlock: |-
      server {
        server_name proxy.lazebny.io;
        listen 0.0.0.0:8080;

        location /discord-api/ {
          proxy_pass https://discord.com/api/;
          proxy_set_header Host discord.com;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /discord-ws/ {
          proxy_pass https://gateway.discord.gg;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host gateway.discord.gg;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
