apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami-nginx
        namespace: flux-system
  interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: nginx-value-overrides
      valuesKey: values.yaml