---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: CF_API_EMAIL
        value: miskadl09@gmail.com
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
    extraArgs:
      - --annotation-filter=external-dns.kubernetes.io/target
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --cloudflare-dns-records-per-page=5000
    # policy: sync
    sources: ["crd", "ingress", "service"]
    # txtPrefix: k8s.
    # txtOwnerId: default
    # domainFilters: ["${SECRET_DOMAIN}"]
    # serviceMonitor:
      # enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: cloudflare-api-token
