---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    # Replace the email address with your own contact email
    email: miskadl09@gmail.com
    # staging server for testing
    # produces valid certificates, but they are not trusted by browsers
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - themisha.dev
        dns01:
          cloudDNS:
            project: learning-383919
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # Replace the email address with your own contact email
    email: miskadl09@gmail.com
    # production server
    # produces trusted certificates
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - themisha.dev
        dns01:
          cloudDNS:
            project: learning-383919
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
---