---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    # Replace the email address with your own contact email
    email: miskadl09@gmail.com
    # staging server for testing
    # produces valid certificates, but they are not trusted by browsers
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # Replace the email address with your own contact email
    email: miskadl09@gmail.com
    # production server
    # produces trusted certificates
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: sandbox
#  namespace: cert-manager
#spec:
#  secretName: sandbox-tls
#  commonName: sandbox
#  issuerRef:
#    name: sandbox-ca
#    kind: Issuer
#    group: cert-manager.io
#  secretTemplate:
#    annotations:
#      kubed.appscode.com/sync: "cert-manager-tls=sandbox" # Sync certificate to matching namespaces