apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - sealed-secret-weawe-gitops.yaml
  - helmrelease-weave-gitops.yaml
  - ../../flux/repositories/oci/weave-gitops.yaml
  - ingress-weave-gitops.yaml
