apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lazebny-io
  namespace: networking
spec:
  secretName: lazebny-io
  commonName: "lazebny.io"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "lazebny.io"
    - "*.lazebny.io"