---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  interval: 1h0m0s
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      hosts: 
        - host: weave.themisha.dev
          paths: 
            - path: /(.*)
              pathType: Prefix
    service:
      create: true
      type: ClusterIP
      port: 9001

  valuesFrom:
    - kind: Secret
      name: weave-gitops-values
      valuesKey: values.yaml