apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: weave-gitops
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgAp1Rs/2kRLoVkwc0JKbZhcYM2sPm5j88u1hmGG6Ycrhr8mWywrc2B+oDzky7S7APrdRlmgW0/bydg/lszr+jWDCzGMiSTjgknYawW+Iqpnte7JAA/5Tq8UB9VcxJ35TJaIJ/qA587nsgiV8HbIN2qcBE1hgUeOewjhJwRKF6dvFXBFwGtP8i80yoH+GjWSkMWDAeZQc/oph35Lgg1T/2dhNqCBFC8Y/gsE2U11J7qPApZzERWfhV6x/iqPRMdqEW5JN6JIc0cHPvSJWPSUF69XufMQ3rCGIm6lGAM0RGjKZwLO7OrImPS1YyvD0oIpEo1Do0G+39IQ3nwa6Jgc33tHJq/EkdoLNX89wGrju4qMg4cc04+aHaT0LjzjTNBCGTOpLnqAjr62DM6iFXgJQe6UtWibUO1Bi+nSKOa1Rc9lz1YCHF70WKRwGabjrpzqFCeb2elfPGPyLUCSqLa/q3Vgqu5yMmceakaDNeEhSI72Z/kAB+Z/FyoR2p4zaynviCAk+lmqsqZ8G57a2sgVjbRMCWsQ3PSnXC+kTnkDN7IzMBQmg6SBPs7ysShl07V/3rRQflSQ7MD9jECpRwX7S/7/9Zt/K89Nf4xphiBiAmrej8Lc28wToicSIjiyIyjDN+ByxPdNX8LFnSA9UN/m8ZnvFRmDqNMHKsmnJQAptyZsbpX+mMS69QxaRWFuhPoRva/+fBpm0Y9wKfQ3I5o43yngekxxfR4qy2OdYcRI6Ov00LV46wv7hEmSssuvsTWM/Oezz71+vJKn01HztBrPwUqIFBxZFttd6Nfvtp0YiVmRJlKFSYK95qY4xyxiq6cqDqaUNAM1Wk3JwwCPc8OpYNpNGMh9r8k7kM+1P5FFemac6BUtHO7eYZdNncig0/Mr896vtGc9aNsvvR/b20F2NVoE
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: weave-gitops
      namespace: flux-system

