apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: weave-gitops-values
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgBiwRMlb6S/h0rpodAhIX2ulNEk66NsawYjan6J26tLCwCmzI9RjagNgJ6dXNoeal3f+smDWGhRyZzKH/vrXs87xS2iv2znsdGU+iFXAUovyB3gxFgFgpcvh4vHubrn9/MBh01Qy3hHqnz6QHZ2pie+biOw2cjcnXGhD/A1XWpxe4F2WSF4kZizR7XWKtIYKi2Tajvo7KsILTSnUdVRkppAtgtRxMV40v5QERINBcfh0oC7HS5bZPvm/AIvotgVU4AZyHufD4Pn8EOw/OzAhYjY3IAx6+Fexk/+wvy6X4DYGYhuB119QR2CT4uv75gqg2967nVa4ITKZoE0DGoDwmhwAKW8SLjFshMPq7jGv6EvzkGNokRfsnUSi/wrwKaPvtv0eVly7Qf+3UyYEy09q1TYCmwbV4OCAm4h5QAzlMakRFWAx9MkRnnC/TC2D2dHhGPrALp4/AA9PL0PA2tJrLoCal2E14m4cJ5AxXhAHXOM89l2I7tnnw/xYbPpRVO4nk4sUQR+GCpoFrWr7sAJ+OZy/iXXHwz0gK6EV6Xe7rprh9Vyd9zqKiVgtbTAnQFGsRPS1KoD5bsD1ZS+sx/VFjEuxR9FAC9EpgzAJBwBpDQIXK+43L7Ji4avnZwFZN1ZD2m1xv376MLRSZWifkl0pHEVuJWGv1A+SEFPBkwLWzvYMfMtstaAiX7KryueH1iC+Coxv5OQ2jnoDpHKL+fYbXTbujXYXBLq5/199VG54CedQMKxUT4IqG92wG7ekFhRA6aTu8KRemGSU4CktUQrqRI1FZFdrDudynOYNxyv4atZrfKc10OuzKjfeYfjtm5A3OcUG2YDaRN2qg9nl8itqY/2KtKMiz/LokZT/2CBFhqO6PvXo9+YkG8FRm92HrPS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: weave-gitops-values
      namespace: flux-system

