apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: weave-gitops-values
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgAHa5DGcakBVi8nvJRjdt3Y04EDeo5MBomDvd8N0VHw3fx/HFEom+4yiMwE+xdx3S1XeGbTTjGKLQSCzn1ZPskeVnb9WchvCg0IK40aTsnX+El6/1ImD5HegQ2DHd8UlP+DXmc7NKfdF8chrM10J0eD8/8nfODNeJR/AaqAhGsqMGUglN3Qkbzaf8gfKYxiU1dGc69QkBT6lzpT4ejTInAE/mJAS8Spf6/0ICXhPfrLNmHbK+A/QBO3uWvWxILG0/DKZ9xHmJeisRF73/j9vYC2bJ6+r/Mg7L5cBFmy5fTsGpYDSkfeLW61XlqdpUxNxAfMIxttQoLlY0DcdBAFfI2//Voroy3g6hwE8kKfMpsbvoU0GrTMw/G3xFl/Ec5OBL4usBmzjbLwviPf/B1X7fVmG3XS/j2aogRnhPp81MHVGWXtem+MbJ33SG9vI1Bo3UfG1RxJzx7IW+ra3pPD+ktl5+odR6Z0yqQn8MaYO04gL1+FSHBUcmMmuUCZW+Zxr8oC0kgy9IWskJ9Oogh0dubTrHT5JlH7d2jr/QUAvuFo68gGDPyLvudvqJggsORhlttg4rhlepGTasxeqRZzNfU5YT6oJ9Q3maj1YjYYyGsao8Yj5Ods2YcU1ax9AQcTNhEKijlDswqDmdKSzi145MaMwHq7qSZiZnmLsEIBwz7fJDdLpRsH/xeoG9oPrCzpFDRMSz5AnEDpc29KUNZ+17QnyEr+dwb5eKrypO6EV3lm6Gs8Q11HI4g5UvhniH0ombVMtMcLfF4jw7SfqpkzQAhmahjh021l2SBOA9p1vTnkXt+MplBcvGEzYKXyNWLKdqF7od9/4Da5oZPdJZ1LWta/sXfP2b0C/+PQGejjHLCGP2O22ED4n8diYQ4IEc/gWw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: weave-gitops-values
      namespace: flux-system

