apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:BEG3wM5PEGGvCj0raJJVRAOnlXVvcIGDMGrP6s3MZoVGBg3Qn3DCPqM4cHC74OYKwpQhfPL3f+2tvuyyeygwpNDWnYSjYywqoLZXvZd2riMvUTM0+4tnHbiRWPC74BuzznnI9iJ1ZYJgmxvKmuo=,iv:hxIsUw6RqcEBakqNNnnwc0BN3QdbRvHtt7u6qsEvOa4=,tag:+O9PQc6MOXkeCgOs7B5sOA==,type:str]
kind: Secret
metadata:
    name: weave-gitops-values
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wuhwmhppza9qpv9xmu9wp8pt399q687y28ftwjkhx7tv4cs7vf3qmt8fr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3citOMFBGcEhiVFphRVBz
            a2d1cnBHZHNWYTBNM3R6akJaL3ZqMEx1ZVUwCjhQRDJkRXY2T2ZLaWplWnRNZ0dO
            a1RQOTBoVlpSUi91OFVBNUVXWkhjUXcKLS0tIE5lWUdSVU5kbUptbzJEbWRyTTVj
            enhDNTZjaW9Xc1RrZFU4dEk2Mk0wSjAKHp7x+IW68gUyJ4wY498eYc0hTKhlO/I9
            m0ThyAgt4sKYoEFDe/ZfSEr+IMxbGt+CiRi1to6qBd4E4BiSwS/W5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-21T13:42:07Z"
    mac: ENC[AES256_GCM,data:xJ8LNuv5fkBmlW2EOZiUlja/lbhwHlHBuvscJm50zIcqP5GQO3DzU2T99zH68dfrQCnLXxkWk5wq8cTBJEUb2soY0yqI1TbvtKZ8lcZwLC0oteNUBGRufGGESe+7sEBXhZNsm0lqR8zd0w3aPqILGXb3CX+Xwf4OICEsWcYeV0Q=,iv:f5d6oRM8roLdmS1wS4Ec1sywFy5yFJjB5+6N5xJThiY=,tag:2hK/QJJ37/H7fJY7YQYlww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
