apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-value-overrides
  namespace: ghost
data:
  values.yaml: |
    ghost:
      nodeEnv: development
      timezone: UTC
      url: https://themisha.dev
      image:
        repository: ghost
        tag: 5.44.0-alpine
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        port: 80
    
    # litestream is a tool for replicating SQLite databases to S3
    litestream:
      enabled: false
      image:
        repository: litestream/litestream
        tag: latest
        pullPolicy: IfNotPresent
      awsSecretRef: aws-credentials
      replicatePathS3: "themisha-dev/ghost.db"
    
    database:
      # Supported databases: sqlite3, mysql
      size: 8Gi
      sqlite3:
        enabled: false
        connection:
          filename: /var/lib/ghost/content/data/ghost.db
          mount: /var/lib/ghost/content/data
      mysql:
        enabled: true
        image:
          repository: mysql
          tag: 8.0.33-debian
          pullPolicy: IfNotPresent
        connection:
          # mysql-database
          # mysql-username
          # mysql-password
          # mysql-root-password
          privateSecretRef: ghost-mysql
        mount: /var/lib/mysql
