apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-value-overrides
  namespace: ghost
data:
  values.yaml: |
    ghost:
      nodeEnv: development
      timezone: UTC
      url: https://themisha.dev
      image:
        repository: ghost
        tag: 5.44.0-alpine
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        port: 80
      mail:
        from: "themisha.dev <"
        transport: SMTP
        host: smtp.gmail.com
        port: 587
        auth:
          username: ""
          password: ""
          # or use secret reference for password and
          privateSecretRef: ghost-mail
    
    mysql:
      size: 8Gi
      image:
        repository: mysql
        tag: 8.0.33-debian
        pullPolicy: IfNotPresent
      connection:
        # mysql-database
        # mysql-username
        # mysql-password
        # mysql-root-password
        privateSecretRef: ghost-mysql
      mount: /var/lib/mysql
