apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-value-overrides
  namespace: ghost
data:
  values.yaml: |
    ghost:
      nodeEnv: production

    service:
      type: ClusterIP
      port: 80

    container:
      image:
        repository: ghost
        tag: 5.44.0-alpine
        pullPolicy: IfNotPresent

    database:
      client: sqlite3