apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  releaseName: ghost
  chart:
    spec:
      chart: bitnami/ghost
      sourceRef:
        kind: HelmRepository
        name: ghost-repository
  interval: 15m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: ghost-value-overrides