apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  releaseName: ghost
  chart:
    spec:
      chart: ghost
      version: 0.33.0
      sourceRef:
        kind: HelmRepository
        name: selfhosted-manifests
        namespace: default
  interval: 15m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: ghost-value-overrides