apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-value-overrides
  namespace: podinfo
data:
  values.yaml: |
    resources:
      requests: 
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 10m
        memory: 100Mi