apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-ingress
  namespace: podinfo
spec:
  releaseName: podinfo-ingress
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: HelmRepository
        name: selfhosted-manifests
        namespace: default
  interval: 15m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      name: "podinfo-ingress"
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      hosts:
        - host:
          paths:
            - path: /podinfo/(.*)
              pathType: Prefix
              serviceName: "podinfo"
              servicePort: 9898
