apiVersion: v1
data:
    SECRET_KEY: ENC[AES256_GCM,data:bjcILao5k9DGKAZH2OrLKQ==,iv:EVIGRtRmwsmQUY4hSNrcoYO5LRP/XUj2qdycimEY3oM=,tag:Ln9+lkBEbdMRSO6RMIk82g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: auther-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wuhwmhppza9qpv9xmu9wp8pt399q687y28ftwjkhx7tv4cs7vf3qmt8fr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS0ZIbUdmVjlVd2Z1M00y
            WEQ5NzlrREFpOWxHSy9FUHkyVEFCRHNneEdVCmVlWURPMWJzSGJHTkt4a2xlZDdt
            YzRWOFRtS0RwS3V0bVNCTGNpL2p1eEkKLS0tIDlQZ0tpVFJDOVFaUkNEN0tabWxP
            cjdkZHoyMmVCdzM3bFdwcUdZR050V2sKxbEVeaNKRo/kfTSlv7CE/EplBSbf3DEv
            sXTHbIhnf+yCLWvmoA+ol3n8MqYszzq5Fh/ZiNK/HAlgyJ5snMEEVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T17:11:36Z"
    mac: ENC[AES256_GCM,data:MLmF7OVHsX8GT8dhhSrLr0wFP3rJXXpA3d0zyJjWbBMUVJj9W5Yw8Z4EgX2+aHkaS8Sh97ezO4mLmQhEH64lybfbx0pEpVESdL0hFSB64hG3UO8QGn8wZ65RbNvMtFNViidpdg6C8qnbVP9VQVvk8scf0qOYmuTGbwDrK1sdErc=,iv:0mVdJb/IxDFYgfoDtV9WJpSfOyBC3u08fhB37UEg8bs=,tag:ptWASVSqZd4be1j0gqiOWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
