apiVersion: v1
data:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:kfmoJUptrXSL8btRRCsCQCEKZDtD1XOt97Jyog==,iv:ic8wClvYLgMalXuW+ba2kvxtTI/A9m/yjuUF7v1TXTY=,tag:2mKibqjvoP4ZW+MAC+SvjA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:j2M4iFLRMa8EfnZSdTP1yg==,iv:+T9fzFJNCvl6b+1Kgkt155A1b2dhn+Y6KsomCq/XkOY=,tag:lD15edf1y2Hjf7MvFdp+LQ==,type:str]
    S3_REGION: ENC[AES256_GCM,data:VPf78cowYZT696tLyHUKDA==,iv:UvGqusVA6o6VjmfBvI3w7wwXOqmBMp13NnTZWPCYGZY=,tag:WQxEeXfgoIdeldiirtMvJg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FXQsnHTnpm3ACqaTW9K9+Ps4+5uKRfiCW56fgiuHv5m7BZjMzmKTKn8ugcFY7MQLMkBA1XbEbxY=,iv:Y82dm3TNEzsTZ6kRSYQl4ScP/U9vp+7YOdlaHOyD/Pw=,tag:c8qziTMC+jsDfuuBWeo5KQ==,type:str]
kind: Secret
metadata:
    name: ghost-backup
    namespace: ghost
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wuhwmhppza9qpv9xmu9wp8pt399q687y28ftwjkhx7tv4cs7vf3qmt8fr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY1BqK3FDczdFZTNnUUl2
            cytNSkZrMzVLNUVhOElLYTYwWUZFYWp6Nm1VCklka3I4VnpiTHJwdnl4WWtzOWtC
            Sit2OHFybHRSNE1DRUsvdjEyNjhQcEUKLS0tIDI1bVhDbDE5L0RvdmlsZkE4YVN3
            blJJVms0dDlxWlIwbGVKaFc2dVhLak0Ko9GHgsA5N33gQ4JX51ndmnTNvsBEtcYr
            AuQnNu+QXBoz2AqVvPlebE9njYyPrHP2l/0B0KOXy0Px8zI7aUSXhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T08:49:59Z"
    mac: ENC[AES256_GCM,data:ipi86Wvi6qTKlekkudfIdpWryMuHwqJeBPubuh2OGOIWS3k+5MMbHwvQQ/wUm3wc1UK5eeoCxvizqdFw0iHdUdk+y0+kQoUqe1LNobXgo0Uy+P2ssYlZzA9Y+4LQogA/wuSxa820YO0VZhw6ZEMGP5vus3qH1aqQRXnIyCcxYDE=,iv:ss7QsGay4dFqP4WDOM31OrujCAPFskWTABNTc1IxbF8=,tag:TVbcUgvvkmSB6I3do/jjXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
