apiVersion: v1
data:
    sops: ENC[AES256_GCM,data:1yIDSp+TCRw=,iv:lL6Sasim70UVmFx753+ku+VcoNSAE9jHXwLKN91G8cY=,tag:OvKZz05ladQWRdOvYHc5LQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sopstest
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kj3f5jk9mmpvjc9srkkwr7medcvvzzym80dx5mj6uu3xn7jhqys0rqwr2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjI0dnFZT0JkOXhpNm1H
            OTlLK0RtOEhINnU3YUZZSWdiQytkdEV1WmtVCnpnaFp3L2VmYm5PV1ZqL21wS3Vz
            Y2lGa2NzY0syQ01kRldpSm5xajRXZHMKLS0tIFE5aUZzR09yK0lUQVUycWlwaXVE
            R1F5Q3dieDYrQml4Y0RCSHRvMk9tNzgKFCkAeE6KViGlWjaLhvZnB/0KiEBpipxe
            RvIYeo4yWPQfYSs5/4HEw2gcJEXQcZt6QYWgKlXNG+Wt6j7QNYgHwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T14:24:56Z"
    mac: ENC[AES256_GCM,data:3RcB2x8QL0KsFHwg0zvT/KaMBlec/vley8LKFEjjhm7ns0tzTeKxZwH2Gtq5o5gGW6XaZ5sxSRu+EZ3WoBTWeipFFDnbYif0RL3/vkqz7iDq2b01P/e32tAUxwkLaUHUBAvWL/9bg39CksScvEOhNDrF/xiCoyB3hWvEUvHrwkc=,iv:Yg9RES+KeSy6RKVgwlQV4uGUz/PELdWJxr22I991yEQ=,tag:5/lY2Hei7s4ne9g2sQZ8iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
