apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-ingress
  namespace: default
spec:
  releaseName: sample-ingress
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: HelmRepository
        name: selfhosted-manifests
        namespace: default
  interval: 15m
  install:
    remediation:
      retries: 3
  values:
    ingress:  
      name: "sample-ingress"
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        - hosts:
            - test.themisha.dev
          secretName: test.themisha.dev
      hosts:
        - host: test.themisha.dev
          paths:
            - path: /sample/(.*)
              pathType: Prefix
              serviceName: "sampleapp"
              servicePort: 9944
