apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample
  namespace: default
spec:
  interval: 5m
  url: https://github.com/hawkkiller/selfhosted-manifests
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: sample
  path: "./sample"
  prune: true
  timeout: 1m