apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample
  namespace: default
spec:
  interval: 5m
  url: https://github.com/hawkkiller/selfhosted-manifests
  ref:
    branch: main