network:
  ip_range: "10.0.0.0/16"
  name: "hcloud-network"
  zone: "eu-central"
  lb:
    name: "hcloud-lb"
    type: "lb11"
    algorithm: "round_robin"
    location: "fsn1"
control_planes:
  - name: "hcloud-control-plane-1"
    type: "cax21"
    location: "fsn1"
workers:
  - name: "hcloud-worker-1"
    type: "cax11"
    location: "fsn1"
image_id: "112442176"
cluster_name: "lazebny-io-cluster"
