apiVersion: v1
kind: ConfigMap
metadata:
  name: percona-value-overrides
data:
  values.yaml: |
    allowUnsafeConfigurations: true
    sharding:
      enabled: false
    pxc:
      size: 1
      volumeSpec:
        pvc:
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
    logcollector:
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
    haproxy:
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
    backup:
      enabled: false