apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost-mysql-cluster
spec:
  releaseName: ghost-mysql-cluster
  chart:
    spec:
      chart: mysql-innodbcluster
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
        namespace: flux-system
  interval: 15m
  values:
    credentials:
      root:
        user: "root"
        password: "password"
        host: "%"
    serverInstances: 1
    routerInstances: 1
