apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost-mysql-cluster
spec:
  releaseName: ghost-mysql-cluster
  chart:
    spec:
      chart: pxc-db
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
  interval: 15m
