apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: default
spec:
  releaseName: ingress
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: HelmRepository
        name: selfhosted-manifests
  interval: 15m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      name: "apps-ingress"